algoritmo "Voto_V2"
var
  idade: inteiro
inicio
escreval("=======================")
escreval("      Posso Votar ?    ")
escreval("=======================")
escreval
escreval
escreval
escreva("Digite sua idade: ")
leia(idade)
se(idade < 16 )entao
escreval ("Nao pode votar")
senao
se(idade = 16)entao
escreval("Voto opcional")
senao
se (idade >= 18)entao
escreval("Voto obrigatorio")
senao
se(idade >= 70)entao
escreval("Voto opcional")
fimse
fimse
fimse
fimse

fimalgoritmo